node "!DOCTYPE" [ attribute "html" "" ]
    [ node "html" [ lang "en" ]
        [ node "head" []
            [ node "meta" [ charset "utf-8" ]
                []
            , node "meta" [ content "IE=edge", attribute "http-equiv" "X-UA-Compatible" ]
                []
            , node "meta" [ content "width=device-width, initial-scale=1", name "viewport" ]
                []
            , node "meta" [ content "", name "description" ]
                []
            , node "meta" [ content "", name "author" ]
                []
            , node "link" [ href "../../favicon.ico", rel "icon" ]
                []
            , node "title" []
                [ text "Bilaval Sharma" ]
            , node "link" [ href "https://fonts.googleapis.com/css?family=Arvo", rel "stylesheet" ]
                []
            , node "link" [ href "fonts/font-awesome/css/font-awesome.min.css", rel "stylesheet" ]
                []
            , node "link" [ href "css/bootstrap.min.css", rel "stylesheet" ]
                []
            , node "link" [ href "../../assets/css/ie10-viewport-bug-workaround.css", rel "stylesheet" ]
                []
            , node "link" [ href "css/stylesheet.css", rel "stylesheet", type_ "text/css" ]
                []
            , text "    "
            ]
        ]
    ]
